import {action, makeAutoObservable, observable, computed} from 'mobx';
import {Placeholder} from '../../../assets';
class ScanTickets {
  @observable currentUser = {};
  constructor() {
    makeAutoObservable(this);
  }

  @action
  setCurrentUser = scanData => {
    this.currentUser = scanData;
  };

  @computed
  isCurrentUserEmpty = () => {
    return Object.keys(this.currentUser).length == 0;
  };

  @computed
  getPurchasedTicketsCount = () => {
    let totalQuantity = 0;
    this.currentUser?.party?.buyTickets?.map(bTicket => {
      totalQuantity += bTicket.selectedQuantity;
    });
    return totalQuantity;
  };
  @computed
  getCurrentScanDetails = () => {
    let userAvatar = Placeholder;
    if (this.currentUser?.user?.profileImage?.filePath) {
      userAvatar = {uri: this.currentUser?.user?.profileImage?.filePath};
    }
    let isPartyFree = this.currentUser?.party?.tickets?.length == 0 ?? 0;
    let purchasedTickets = null;
    let obj = {
      userAvatar,
      userName: this.currentUser.user.fullName,
      ticketLen: isPartyFree ? null : purchasedTickets,
      isAttending: true,
      //this.currentUser?.party?.isAttending ?? false
    };
    return obj;
  };
  static get instance() {
    return new ScanTickets();
  }
}

export default ScanTickets;

var DUMMY_DATA = {
  success: true,
  user: {
    id: 2,
    phoneNumber: '9691344215',
    email: 'guest2@gmail.com',
    fullName: 'Guest 2',
    birthday: '2021-10-13 00:00:00',
    state: null,
    city: null,
    about: null,
    description: null,
    profession: null,
    vendorType: 0,
    age: 0,
    snapchatUsername: null,
    instagramUsername: null,
    tiktokUsername: null,
    twitterUsername: null,
    linkedInUsername: null,
    countryCode: {
      id: 229,
      code: 'US',
      flag: '🇺🇸',
      name: 'United States',
      dial_code: '+1',
    },
    firebaseTokens: [
      'dmd6x1DJA0kNubwR3t1uOc:APA91bHmV52BoVTXjJioou3w1rojAcTl0ZjxbL76DpZCID-yUm4ysRHnor-lGY8wubrCYDGXQP_GWr0kPxJfXOzYEu9wMRkFi43yq5Rt3pWZ9hCKPDNuZuVjt0Wi7aiSPRwtyOFI1_Jx',
    ],
    username: 'guest2',
    gender: null,
    numberOfRatings: 0,
    averageRating: '0',
    instaData: null,
    instaId: null,
    friendCount: false,
    hosting: false,
    attending: false,
    interested: false,
    profileImage: {
      id: 4,
      fileName: 'image-1634712404373.jpg',
      createdAt: '2021-10-20T06:46:45.420Z',
      filePath:
        'https://bounce-prod-media.s3.us-east-2.amazonaws.com/2021-10-20/fb1ffb5081d106d313a17bb3f2ebb7e04c6e19cd/ca576f5ba6bdbcd248bf0a8e1f135a17/image-1634712404373.jpg',
      fileSequence: 0,
    },
    gallery: [],
    language: [],
    mediaGallery: [],
    spotify: null,
    blockedByUsers: [],
    blockedUsers: [],
    userInterest: [
      {
        id: 1,
        name: 'Entertainment',
        subTags: [
          {id: 3, name: 'Clubs', emoji: '🕺'},
          {id: 4, name: 'Game Shows', emoji: '📺'},
          {id: 5, name: 'Gaming', emoji: '🎮'},
        ],
      },
    ],
  },
  party: {
    id: 6,
    createdAt: '2021-10-20T08:30:14.733Z',
    title: 'Thanos birthday party',
    description: 'Desc',
    date: '2021-10-24T13:59:11.000Z',
    isPrivate: false,
    fee: 0,
    needBouncer: false,
    needDJ: false,
    ageLimit: false,
    fromAge: 0,
    toAge: 0,
    isDraft: false,
    creator: {
      id: 1,
      phoneNumber: '8720880991',
      email: 'guest1@gmail.com',
      fullName: 'Guest 1',
      birthday: '2021-10-07 00:00:00',
      state: null,
      city: 'null',
      about: 'null',
      description: null,
      profession: 'null',
      vendorType: 0,
      age: 0,
      snapchatUsername: 'null',
      instagramUsername: null,
      tiktokUsername: 'null',
      twitterUsername: 'null',
      linkedInUsername: 'null',
      countryCode: {
        id: 229,
        code: 'US',
        flag: '🇺🇸',
        name: 'United States',
        dial_code: '+1',
      },
      firebaseTokens: [
        'cHcd8yKoh03zgam9dm9XTq:APA91bFbh0G43VSER_TIYxu1uRHGOd_WowHrxBJ_NLHWLemx2bpEx-Fjyka-nBEaIBhwFI_G6QFEerC5tRcQyhh3zVQVwg9vuKWGAHlmedoYrqv1O_jQ_0evJUjyMPjKUzT8XQ6ekqP3',
      ],
      username: 'guest1',
      gender: null,
      numberOfRatings: 0,
      averageRating: '0',
      instaData: null,
      instaId: null,
      friendCount: false,
      hosting: false,
      attending: false,
      interested: false,
      profileImage: {
        id: 27,
        fileName: 'image-1634830879802.jpg',
        createdAt: '2021-10-21T15:43:16.800Z',
        filePath:
          'https://bounce-prod-media.s3.amazonaws.com/2021-10-21/3c9bee1b7a2f9f503f217e9d9175514ea49957a1/9c991b6f121ecdb233e2fb4385ec90d1/image-1634830879802.jpg',
        fileSequence: 0,
      },
    },
    location: {id: 6, lon: '1', lat: '1', addressStr: 'Address'},
    profileImage: {
      id: 18,
      fileName: '00532B40-EE22-4C12-AEEE-EAC0299CCA61.jpg',
      createdAt: '2021-10-20T08:30:14.647Z',
      filePath:
        'https://bounce-prod-media.s3.us-east-2.amazonaws.com/2021-10-20/24e92d8228f03951951ba6be80cf69444f0fc55d/1c1335d236faa469a8e58e721b719b62/00532B40-EE22-4C12-AEEE-EAC0299CCA61.jpg',
      fileSequence: 0,
    },
    gallery: [
      {
        id: 19,
        fileName: '00532B40-EE22-4C12-AEEE-EAC0299CCA61.jpg',
        createdAt: '2021-10-20T08:30:14.703Z',
        filePath:
          'https://bounce-prod-media.s3.us-east-2.amazonaws.com/2021-10-20/ce49dcae30c4acba6a245ce3456c9d343a424a39/1c1335d236faa469a8e58e721b719b62/00532B40-EE22-4C12-AEEE-EAC0299CCA61.jpg',
        fileSequence: 0,
        uploader: {
          id: 1,
          phoneNumber: '8720880991',
          email: 'guest1@gmail.com',
          fullName: 'Guest 1',
          birthday: '2021-10-07 00:00:00',
          state: null,
          city: 'null',
          about: 'null',
          description: null,
          profession: 'null',
          vendorType: 0,
          age: 0,
          snapchatUsername: 'null',
          instagramUsername: null,
          tiktokUsername: 'null',
          twitterUsername: 'null',
          linkedInUsername: 'null',
          countryCode: {
            id: 229,
            code: 'US',
            flag: '🇺🇸',
            name: 'United States',
            dial_code: '+1',
          },
          firebaseTokens: [
            'cHcd8yKoh03zgam9dm9XTq:APA91bFbh0G43VSER_TIYxu1uRHGOd_WowHrxBJ_NLHWLemx2bpEx-Fjyka-nBEaIBhwFI_G6QFEerC5tRcQyhh3zVQVwg9vuKWGAHlmedoYrqv1O_jQ_0evJUjyMPjKUzT8XQ6ekqP3',
          ],
          username: 'guest1',
          gender: null,
          numberOfRatings: 0,
          averageRating: '0',
          instaData: null,
          instaId: null,
          friendCount: false,
          hosting: false,
          attending: false,
          interested: false,
          profileImage: {
            id: 27,
            fileName: 'image-1634830879802.jpg',
            createdAt: '2021-10-21T15:43:16.800Z',
            filePath:
              'https://bounce-prod-media.s3.amazonaws.com/2021-10-21/3c9bee1b7a2f9f503f217e9d9175514ea49957a1/9c991b6f121ecdb233e2fb4385ec90d1/image-1634830879802.jpg',
            fileSequence: 0,
          },
        },
      },
    ],
    likes: [
      {
        id: 2,
        phoneNumber: '9691344215',
        email: 'guest2@gmail.com',
        fullName: 'Guest 2',
        birthday: '2021-10-13 00:00:00',
        state: null,
        city: null,
        about: null,
        description: null,
        profession: null,
        vendorType: 0,
        age: 0,
        snapchatUsername: null,
        instagramUsername: null,
        tiktokUsername: null,
        twitterUsername: null,
        linkedInUsername: null,
        countryCode: {
          id: 229,
          code: 'US',
          flag: '🇺🇸',
          name: 'United States',
          dial_code: '+1',
        },
        firebaseTokens: [
          'dmd6x1DJA0kNubwR3t1uOc:APA91bHmV52BoVTXjJioou3w1rojAcTl0ZjxbL76DpZCID-yUm4ysRHnor-lGY8wubrCYDGXQP_GWr0kPxJfXOzYEu9wMRkFi43yq5Rt3pWZ9hCKPDNuZuVjt0Wi7aiSPRwtyOFI1_Jx',
        ],
        username: 'guest2',
        gender: null,
        numberOfRatings: 0,
        averageRating: '0',
        instaData: null,
        instaId: null,
        friendCount: false,
        hosting: false,
        attending: false,
        interested: false,
        profileImage: {
          id: 4,
          fileName: 'image-1634712404373.jpg',
          createdAt: '2021-10-20T06:46:45.420Z',
          filePath:
            'https://bounce-prod-media.s3.us-east-2.amazonaws.com/2021-10-20/fb1ffb5081d106d313a17bb3f2ebb7e04c6e19cd/ca576f5ba6bdbcd248bf0a8e1f135a17/image-1634712404373.jpg',
          fileSequence: 0,
        },
      },
    ],
    hosts: [
      {
        id: 6,
        createdAt: '2021-10-20T08:30:15.878Z',
        status: 1,
        setByUser: {
          id: 1,
          phoneNumber: '8720880991',
          email: 'guest1@gmail.com',
          fullName: 'Guest 1',
          birthday: '2021-10-07 00:00:00',
          state: null,
          city: 'null',
          about: 'null',
          description: null,
          profession: 'null',
          vendorType: 0,
          age: 0,
          snapchatUsername: 'null',
          instagramUsername: null,
          tiktokUsername: 'null',
          twitterUsername: 'null',
          linkedInUsername: 'null',
          countryCode: {
            id: 229,
            code: 'US',
            flag: '🇺🇸',
            name: 'United States',
            dial_code: '+1',
          },
          firebaseTokens: [
            'cHcd8yKoh03zgam9dm9XTq:APA91bFbh0G43VSER_TIYxu1uRHGOd_WowHrxBJ_NLHWLemx2bpEx-Fjyka-nBEaIBhwFI_G6QFEerC5tRcQyhh3zVQVwg9vuKWGAHlmedoYrqv1O_jQ_0evJUjyMPjKUzT8XQ6ekqP3',
          ],
          username: 'guest1',
          gender: null,
          numberOfRatings: 0,
          averageRating: '0',
          instaData: null,
          instaId: null,
          friendCount: false,
          hosting: false,
          attending: false,
          interested: false,
          profileImage: {
            id: 27,
            fileName: 'image-1634830879802.jpg',
            createdAt: '2021-10-21T15:43:16.800Z',
            filePath:
              'https://bounce-prod-media.s3.amazonaws.com/2021-10-21/3c9bee1b7a2f9f503f217e9d9175514ea49957a1/9c991b6f121ecdb233e2fb4385ec90d1/image-1634830879802.jpg',
            fileSequence: 0,
          },
        },
        host: {
          id: 1,
          phoneNumber: '8720880991',
          email: 'guest1@gmail.com',
          fullName: 'Guest 1',
          birthday: '2021-10-07 00:00:00',
          state: null,
          city: 'null',
          about: 'null',
          description: null,
          profession: 'null',
          vendorType: 0,
          age: 0,
          snapchatUsername: 'null',
          instagramUsername: null,
          tiktokUsername: 'null',
          twitterUsername: 'null',
          linkedInUsername: 'null',
          countryCode: {
            id: 229,
            code: 'US',
            flag: '🇺🇸',
            name: 'United States',
            dial_code: '+1',
          },
          firebaseTokens: [
            'cHcd8yKoh03zgam9dm9XTq:APA91bFbh0G43VSER_TIYxu1uRHGOd_WowHrxBJ_NLHWLemx2bpEx-Fjyka-nBEaIBhwFI_G6QFEerC5tRcQyhh3zVQVwg9vuKWGAHlmedoYrqv1O_jQ_0evJUjyMPjKUzT8XQ6ekqP3',
          ],
          username: 'guest1',
          gender: null,
          numberOfRatings: 0,
          averageRating: '0',
          instaData: null,
          instaId: null,
          friendCount: false,
          hosting: false,
          attending: false,
          interested: false,
          profileImage: {
            id: 27,
            fileName: 'image-1634830879802.jpg',
            createdAt: '2021-10-21T15:43:16.800Z',
            filePath:
              'https://bounce-prod-media.s3.amazonaws.com/2021-10-21/3c9bee1b7a2f9f503f217e9d9175514ea49957a1/9c991b6f121ecdb233e2fb4385ec90d1/image-1634830879802.jpg',
            fileSequence: 0,
          },
        },
      },
    ],
    attending: [
      {
        id: 2,
        phoneNumber: '9691344215',
        email: 'guest2@gmail.com',
        fullName: 'Guest 2',
        birthday: '2021-10-13 00:00:00',
        state: null,
        city: null,
        about: null,
        description: null,
        profession: null,
        vendorType: 0,
        age: 0,
        snapchatUsername: null,
        instagramUsername: null,
        tiktokUsername: null,
        twitterUsername: null,
        linkedInUsername: null,
        countryCode: {
          id: 229,
          code: 'US',
          flag: '🇺🇸',
          name: 'United States',
          dial_code: '+1',
        },
        firebaseTokens: [
          'dmd6x1DJA0kNubwR3t1uOc:APA91bHmV52BoVTXjJioou3w1rojAcTl0ZjxbL76DpZCID-yUm4ysRHnor-lGY8wubrCYDGXQP_GWr0kPxJfXOzYEu9wMRkFi43yq5Rt3pWZ9hCKPDNuZuVjt0Wi7aiSPRwtyOFI1_Jx',
        ],
        username: 'guest2',
        gender: null,
        numberOfRatings: 0,
        averageRating: '0',
        instaData: null,
        instaId: null,
        friendCount: false,
        hosting: false,
        attending: false,
        interested: false,
        profileImage: {
          id: 4,
          fileName: 'image-1634712404373.jpg',
          createdAt: '2021-10-20T06:46:45.420Z',
          filePath:
            'https://bounce-prod-media.s3.us-east-2.amazonaws.com/2021-10-20/fb1ffb5081d106d313a17bb3f2ebb7e04c6e19cd/ca576f5ba6bdbcd248bf0a8e1f135a17/image-1634712404373.jpg',
          fileSequence: 0,
        },
      },
      {
        id: 1,
        phoneNumber: '8720880991',
        email: 'guest1@gmail.com',
        fullName: 'Guest 1',
        birthday: '2021-10-07 00:00:00',
        state: null,
        city: 'null',
        about: 'null',
        description: null,
        profession: 'null',
        vendorType: 0,
        age: 0,
        snapchatUsername: 'null',
        instagramUsername: null,
        tiktokUsername: 'null',
        twitterUsername: 'null',
        linkedInUsername: 'null',
        countryCode: {
          id: 229,
          code: 'US',
          flag: '🇺🇸',
          name: 'United States',
          dial_code: '+1',
        },
        firebaseTokens: [
          'cHcd8yKoh03zgam9dm9XTq:APA91bFbh0G43VSER_TIYxu1uRHGOd_WowHrxBJ_NLHWLemx2bpEx-Fjyka-nBEaIBhwFI_G6QFEerC5tRcQyhh3zVQVwg9vuKWGAHlmedoYrqv1O_jQ_0evJUjyMPjKUzT8XQ6ekqP3',
        ],
        username: 'guest1',
        gender: null,
        numberOfRatings: 0,
        averageRating: '0',
        instaData: null,
        instaId: null,
        friendCount: false,
        hosting: false,
        attending: false,
        interested: false,
        profileImage: {
          id: 27,
          fileName: 'image-1634830879802.jpg',
          createdAt: '2021-10-21T15:43:16.800Z',
          filePath:
            'https://bounce-prod-media.s3.amazonaws.com/2021-10-21/3c9bee1b7a2f9f503f217e9d9175514ea49957a1/9c991b6f121ecdb233e2fb4385ec90d1/image-1634830879802.jpg',
          fileSequence: 0,
        },
      },
    ],
    cantgo: [],
    arrived: [
      {
        id: 1,
        phoneNumber: '8720880991',
        email: 'guest1@gmail.com',
        fullName: 'Guest 1',
        birthday: '2021-10-07 00:00:00',
        state: null,
        city: 'null',
        about: 'null',
        description: null,
        profession: 'null',
        vendorType: 0,
        age: 0,
        snapchatUsername: 'null',
        instagramUsername: null,
        tiktokUsername: 'null',
        twitterUsername: 'null',
        linkedInUsername: 'null',
        countryCode: {
          id: 229,
          code: 'US',
          flag: '🇺🇸',
          name: 'United States',
          dial_code: '+1',
        },
        firebaseTokens: [
          'cHcd8yKoh03zgam9dm9XTq:APA91bFbh0G43VSER_TIYxu1uRHGOd_WowHrxBJ_NLHWLemx2bpEx-Fjyka-nBEaIBhwFI_G6QFEerC5tRcQyhh3zVQVwg9vuKWGAHlmedoYrqv1O_jQ_0evJUjyMPjKUzT8XQ6ekqP3',
        ],
        username: 'guest1',
        gender: null,
        numberOfRatings: 0,
        averageRating: '0',
        instaData: null,
        instaId: null,
        friendCount: false,
        hosting: false,
        attending: false,
        interested: false,
        profileImage: {
          id: 27,
          fileName: 'image-1634830879802.jpg',
          createdAt: '2021-10-21T15:43:16.800Z',
          filePath:
            'https://bounce-prod-media.s3.amazonaws.com/2021-10-21/3c9bee1b7a2f9f503f217e9d9175514ea49957a1/9c991b6f121ecdb233e2fb4385ec90d1/image-1634830879802.jpg',
          fileSequence: 0,
        },
      },
      {
        id: 2,
        phoneNumber: '9691344215',
        email: 'guest2@gmail.com',
        fullName: 'Guest 2',
        birthday: '2021-10-13 00:00:00',
        state: null,
        city: null,
        about: null,
        description: null,
        profession: null,
        vendorType: 0,
        age: 0,
        snapchatUsername: null,
        instagramUsername: null,
        tiktokUsername: null,
        twitterUsername: null,
        linkedInUsername: null,
        countryCode: {
          id: 229,
          code: 'US',
          flag: '🇺🇸',
          name: 'United States',
          dial_code: '+1',
        },
        firebaseTokens: [
          'dmd6x1DJA0kNubwR3t1uOc:APA91bHmV52BoVTXjJioou3w1rojAcTl0ZjxbL76DpZCID-yUm4ysRHnor-lGY8wubrCYDGXQP_GWr0kPxJfXOzYEu9wMRkFi43yq5Rt3pWZ9hCKPDNuZuVjt0Wi7aiSPRwtyOFI1_Jx',
        ],
        username: 'guest2',
        gender: null,
        numberOfRatings: 0,
        averageRating: '0',
        instaData: null,
        instaId: null,
        friendCount: false,
        hosting: false,
        attending: false,
        interested: false,
        profileImage: {
          id: 4,
          fileName: 'image-1634712404373.jpg',
          createdAt: '2021-10-20T06:46:45.420Z',
          filePath:
            'https://bounce-prod-media.s3.us-east-2.amazonaws.com/2021-10-20/fb1ffb5081d106d313a17bb3f2ebb7e04c6e19cd/ca576f5ba6bdbcd248bf0a8e1f135a17/image-1634712404373.jpg',
          fileSequence: 0,
        },
      },
    ],
    bouncer: null,
    dj: null,
    mediaGallery: [],
    tickets: [
      {
        id: 4,
        createdAt: '2021-10-20T08:30:14.751Z',
        title: 'Title',
        description: 'Desc',
        price: '150',
        quantity: 100,
        soldOut: 2,
      },
    ],
    buyTickets: [
      {
        id: 11,
        paymentId: 'pi_3JmaFNFA7GDhqLcr25JSQDsO',
        title: 'Title',
        description: 'Desc',
        price: 150,
        quantity: 100,
        selectedQuantity: 1,
        totalTicketPrice: '150',
        totalTicketTax: '4.5',
        totalTicketPriceWithTax: '154.5',
        createdAt: '2021-10-20T08:34:17.719Z',
        user: {
          id: 2,
          phoneNumber: '9691344215',
          email: 'guest2@gmail.com',
          fullName: 'Guest 2',
          birthday: '2021-10-13 00:00:00',
          state: null,
          city: null,
          about: null,
          description: null,
          profession: null,
          vendorType: 0,
          age: 0,
          snapchatUsername: null,
          instagramUsername: null,
          tiktokUsername: null,
          twitterUsername: null,
          linkedInUsername: null,
          countryCode: {
            id: 229,
            code: 'US',
            flag: '🇺🇸',
            name: 'United States',
            dial_code: '+1',
          },
          firebaseTokens: [
            'dmd6x1DJA0kNubwR3t1uOc:APA91bHmV52BoVTXjJioou3w1rojAcTl0ZjxbL76DpZCID-yUm4ysRHnor-lGY8wubrCYDGXQP_GWr0kPxJfXOzYEu9wMRkFi43yq5Rt3pWZ9hCKPDNuZuVjt0Wi7aiSPRwtyOFI1_Jx',
          ],
          username: 'guest2',
          gender: null,
          numberOfRatings: 0,
          averageRating: '0',
          instaData: null,
          instaId: null,
          friendCount: false,
          hosting: false,
          attending: false,
          interested: false,
        },
      },
    ],
    partyTags: [
      {
        id: 1,
        name: 'Entertainment',
        subTags: [
          {id: 1, name: 'Concerts', emoji: '🎫'},
          {id: 2, name: 'Comedy', emoji: '🙊'},
          {id: 3, name: 'Clubs', emoji: '🕺'},
          {id: 6, name: 'Bars', emoji: '🍸'},
          {id: 5, name: 'Gaming', emoji: '🎮'},
          {id: 4, name: 'Game Shows', emoji: '📺'},
        ],
      },
    ],
    list: {
      id: 6,
      title: 'Thanos birthday party',
      createdAt: '2021-10-20T08:30:14.748Z',
    },
    hiredVendors: [
      {
        id: 1,
        createdAt: '2021-10-21T11:13:27.268Z',
        host: {
          id: 1,
          phoneNumber: '8720880991',
          email: 'guest1@gmail.com',
          fullName: 'Guest 1',
          birthday: '2021-10-07 00:00:00',
          state: null,
          city: 'null',
          about: 'null',
          description: null,
          profession: 'null',
          vendorType: 0,
          age: 0,
          snapchatUsername: 'null',
          instagramUsername: null,
          tiktokUsername: 'null',
          twitterUsername: 'null',
          linkedInUsername: 'null',
          countryCode: {
            id: 229,
            code: 'US',
            flag: '🇺🇸',
            name: 'United States',
            dial_code: '+1',
          },
          firebaseTokens: [
            'cHcd8yKoh03zgam9dm9XTq:APA91bFbh0G43VSER_TIYxu1uRHGOd_WowHrxBJ_NLHWLemx2bpEx-Fjyka-nBEaIBhwFI_G6QFEerC5tRcQyhh3zVQVwg9vuKWGAHlmedoYrqv1O_jQ_0evJUjyMPjKUzT8XQ6ekqP3',
          ],
          username: 'guest1',
          gender: null,
          numberOfRatings: 0,
          averageRating: '0',
          instaData: null,
          instaId: null,
          friendCount: false,
          hosting: false,
          attending: false,
          interested: false,
          profileImage: {
            id: 27,
            fileName: 'image-1634830879802.jpg',
            createdAt: '2021-10-21T15:43:16.800Z',
            filePath:
              'https://bounce-prod-media.s3.amazonaws.com/2021-10-21/3c9bee1b7a2f9f503f217e9d9175514ea49957a1/9c991b6f121ecdb233e2fb4385ec90d1/image-1634830879802.jpg',
            fileSequence: 0,
          },
        },
        vendor: {
          id: 12,
          phoneNumber: '8720880991',
          email: 'music1@gmail.com',
          fullName: 'Music 1',
          birthday: null,
          state: null,
          city: 'Indore, Madhya Pradesh, India',
          about: 'Desc\t',
          description: null,
          profession: null,
          vendorType: 2,
          age: 1,
          snapchatUsername: null,
          instagramUsername: null,
          tiktokUsername: null,
          twitterUsername: null,
          linkedInUsername: null,
          countryCode: {
            id: 229,
            code: 'US',
            flag: '🇺🇸',
            name: 'United States',
            dial_code: '+1',
          },
          firebaseTokens: null,
          username: 'music1',
          gender: 0,
          numberOfRatings: 1,
          averageRating: '5',
          instaData: null,
          instaId: null,
          friendCount: false,
          hosting: false,
          attending: false,
          interested: false,
          profileImage: {
            id: 25,
            fileName: '5323916A-8CF9-482D-86B3-1F686E32D030.jpg',
            createdAt: '2021-10-21T11:10:53.424Z',
            filePath:
              'https://bounce-prod-media.s3.us-east-2.amazonaws.com/2021-10-21/91b84b2add15719344a3d592aad92dc2c73969f3/acc4c7eedfc7263a57d4e1f1ce432661/5323916A-8CF9-482D-86B3-1F686E32D030.jpg',
            fileSequence: 0,
          },
        },
      },
    ],
    unconfirmedHost: [
      {
        id: 6,
        createdAt: '2021-10-20T08:30:15.878Z',
        status: 1,
        setByUser: {
          id: 1,
          phoneNumber: '8720880991',
          email: 'guest1@gmail.com',
          fullName: 'Guest 1',
          birthday: '2021-10-07 00:00:00',
          state: null,
          city: 'null',
          about: 'null',
          description: null,
          profession: 'null',
          vendorType: 0,
          age: 0,
          snapchatUsername: 'null',
          instagramUsername: null,
          tiktokUsername: 'null',
          twitterUsername: 'null',
          linkedInUsername: 'null',
          countryCode: {
            id: 229,
            code: 'US',
            flag: '🇺🇸',
            name: 'United States',
            dial_code: '+1',
          },
          firebaseTokens: [
            'cHcd8yKoh03zgam9dm9XTq:APA91bFbh0G43VSER_TIYxu1uRHGOd_WowHrxBJ_NLHWLemx2bpEx-Fjyka-nBEaIBhwFI_G6QFEerC5tRcQyhh3zVQVwg9vuKWGAHlmedoYrqv1O_jQ_0evJUjyMPjKUzT8XQ6ekqP3',
          ],
          username: 'guest1',
          gender: null,
          numberOfRatings: 0,
          averageRating: '0',
          instaData: null,
          instaId: null,
          friendCount: false,
          hosting: false,
          attending: false,
          interested: false,
          profileImage: {
            id: 27,
            fileName: 'image-1634830879802.jpg',
            createdAt: '2021-10-21T15:43:16.800Z',
            filePath:
              'https://bounce-prod-media.s3.amazonaws.com/2021-10-21/3c9bee1b7a2f9f503f217e9d9175514ea49957a1/9c991b6f121ecdb233e2fb4385ec90d1/image-1634830879802.jpg',
            fileSequence: 0,
          },
        },
        host: {
          id: 1,
          phoneNumber: '8720880991',
          email: 'guest1@gmail.com',
          fullName: 'Guest 1',
          birthday: '2021-10-07 00:00:00',
          state: null,
          city: 'null',
          about: 'null',
          description: null,
          profession: 'null',
          vendorType: 0,
          age: 0,
          snapchatUsername: 'null',
          instagramUsername: null,
          tiktokUsername: 'null',
          twitterUsername: 'null',
          linkedInUsername: 'null',
          countryCode: {
            id: 229,
            code: 'US',
            flag: '🇺🇸',
            name: 'United States',
            dial_code: '+1',
          },
          firebaseTokens: [
            'cHcd8yKoh03zgam9dm9XTq:APA91bFbh0G43VSER_TIYxu1uRHGOd_WowHrxBJ_NLHWLemx2bpEx-Fjyka-nBEaIBhwFI_G6QFEerC5tRcQyhh3zVQVwg9vuKWGAHlmedoYrqv1O_jQ_0evJUjyMPjKUzT8XQ6ekqP3',
          ],
          username: 'guest1',
          gender: null,
          numberOfRatings: 0,
          averageRating: '0',
          instaData: null,
          instaId: null,
          friendCount: false,
          hosting: false,
          attending: false,
          interested: false,
          profileImage: {
            id: 27,
            fileName: 'image-1634830879802.jpg',
            createdAt: '2021-10-21T15:43:16.800Z',
            filePath:
              'https://bounce-prod-media.s3.amazonaws.com/2021-10-21/3c9bee1b7a2f9f503f217e9d9175514ea49957a1/9c991b6f121ecdb233e2fb4385ec90d1/image-1634830879802.jpg',
            fileSequence: 0,
          },
        },
      },
    ],
    invited: [
      {
        id: 2,
        phoneNumber: '9691344215',
        email: 'guest2@gmail.com',
        fullName: 'Guest 2',
        birthday: '2021-10-13 00:00:00',
        state: null,
        city: null,
        about: null,
        description: null,
        profession: null,
        vendorType: 0,
        age: 0,
        snapchatUsername: null,
        instagramUsername: null,
        tiktokUsername: null,
        twitterUsername: null,
        linkedInUsername: null,
        countryCode: {
          id: 229,
          code: 'US',
          flag: '🇺🇸',
          name: 'United States',
          dial_code: '+1',
        },
        firebaseTokens: [
          'dmd6x1DJA0kNubwR3t1uOc:APA91bHmV52BoVTXjJioou3w1rojAcTl0ZjxbL76DpZCID-yUm4ysRHnor-lGY8wubrCYDGXQP_GWr0kPxJfXOzYEu9wMRkFi43yq5Rt3pWZ9hCKPDNuZuVjt0Wi7aiSPRwtyOFI1_Jx',
        ],
        username: 'guest2',
        gender: null,
        numberOfRatings: 0,
        averageRating: '0',
        instaData: null,
        instaId: null,
        friendCount: false,
        hosting: false,
        attending: false,
        interested: false,
        profileImage: {
          id: 4,
          fileName: 'image-1634712404373.jpg',
          createdAt: '2021-10-20T06:46:45.420Z',
          filePath:
            'https://bounce-prod-media.s3.us-east-2.amazonaws.com/2021-10-20/fb1ffb5081d106d313a17bb3f2ebb7e04c6e19cd/ca576f5ba6bdbcd248bf0a8e1f135a17/image-1634712404373.jpg',
          fileSequence: 0,
        },
      },
    ],
    invite: {
      id: 5,
      createdAt: '2021-10-20T08:30:43.747Z',
      invitedBy: {
        id: 1,
        phoneNumber: '8720880991',
        email: 'guest1@gmail.com',
        fullName: 'Guest 1',
        birthday: '2021-10-07 00:00:00',
        state: null,
        city: 'null',
        about: 'null',
        description: null,
        profession: 'null',
        vendorType: 0,
        age: 0,
        snapchatUsername: 'null',
        instagramUsername: null,
        tiktokUsername: 'null',
        twitterUsername: 'null',
        linkedInUsername: 'null',
        countryCode: {
          id: 229,
          code: 'US',
          flag: '🇺🇸',
          name: 'United States',
          dial_code: '+1',
        },
        firebaseTokens: [
          'cHcd8yKoh03zgam9dm9XTq:APA91bFbh0G43VSER_TIYxu1uRHGOd_WowHrxBJ_NLHWLemx2bpEx-Fjyka-nBEaIBhwFI_G6QFEerC5tRcQyhh3zVQVwg9vuKWGAHlmedoYrqv1O_jQ_0evJUjyMPjKUzT8XQ6ekqP3',
        ],
        username: 'guest1',
        gender: null,
        numberOfRatings: 0,
        averageRating: '0',
        instaData: null,
        instaId: null,
        friendCount: false,
        hosting: false,
        attending: false,
        interested: false,
      },
      invitedUser: {
        id: 2,
        phoneNumber: '9691344215',
        email: 'guest2@gmail.com',
        fullName: 'Guest 2',
        birthday: '2021-10-13 00:00:00',
        state: null,
        city: null,
        about: null,
        description: null,
        profession: null,
        vendorType: 0,
        age: 0,
        snapchatUsername: null,
        instagramUsername: null,
        tiktokUsername: null,
        twitterUsername: null,
        linkedInUsername: null,
        countryCode: {
          id: 229,
          code: 'US',
          flag: '🇺🇸',
          name: 'United States',
          dial_code: '+1',
        },
        firebaseTokens: [
          'dmd6x1DJA0kNubwR3t1uOc:APA91bHmV52BoVTXjJioou3w1rojAcTl0ZjxbL76DpZCID-yUm4ysRHnor-lGY8wubrCYDGXQP_GWr0kPxJfXOzYEu9wMRkFi43yq5Rt3pWZ9hCKPDNuZuVjt0Wi7aiSPRwtyOFI1_Jx',
        ],
        username: 'guest2',
        gender: null,
        numberOfRatings: 0,
        averageRating: '0',
        instaData: null,
        instaId: null,
        friendCount: false,
        hosting: false,
        attending: false,
        interested: false,
        profileImage: {
          id: 4,
          fileName: 'image-1634712404373.jpg',
          createdAt: '2021-10-20T06:46:45.420Z',
          filePath:
            'https://bounce-prod-media.s3.us-east-2.amazonaws.com/2021-10-20/fb1ffb5081d106d313a17bb3f2ebb7e04c6e19cd/ca576f5ba6bdbcd248bf0a8e1f135a17/image-1634712404373.jpg',
          fileSequence: 0,
        },
      },
      party: {
        id: 6,
        createdAt: '2021-10-20T08:30:14.733Z',
        title: 'Thanos birthday party',
        description: 'Desc',
        date: '2021-10-24T13:59:11.000Z',
        isPrivate: false,
        fee: 0,
        needBouncer: false,
        needDJ: false,
        ageLimit: false,
        fromAge: 0,
        toAge: 0,
        isDraft: false,
      },
    },
    isHost: false,
    madeHostBy: null,
    isLiked: true,
    isAttending: true,
    friendsWantsToGo: [],
    isCantGo: false,
    isLive: false,
  },
};
